### ISSUE TITLE
Refactor and create better framework

### ISSUE THREAD

**Issue by jimperio** [jimperio/roguelike#1]
I'm not sure Phaser is exactly the right choice for a game like this with very simple graphics.

Phaser will make it easier to eventually switch to tile graphics, but if we're sticking with ASCII, wouldn't something like React be a better fit? At least for the UI chrome like the sidebar and bottom message display, as well as inventories and menus in the future, React seems like an easier choice.

But as for the game map/screen itself... I suppose it's possible to create a `Tile` React component and build from there.

**Comment by marksteve** [comment]
I can take on initial work on this! :D

**Comment by jimperio** [comment]
Closing this for now. I've at least organized the functions a little bit better (https://github.com/jimperio/roguelike/commit/aa6dca9ca9c63d7e8146fb9b94788cb232d47822), and will improve the organization/framework as I go along.
